version: '3.1'

services:
  
  app:
    image: assorium/js-cdn-images:latest
    restart: always
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${UPLOAD_PATH_HOST}:/home/node/app/upload
    networks:
      - app-network
    labels:
      - com.centurylinklabs.watchtower.enable=1

  webserver:
    image: nginx:latest
    depends_on:
      - app
    container_name: cdn_js_webserver
    restart: unless-stopped
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_PORT=${APP_PORT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template:ro
    networks:
      - app-network
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    labels:
      - com.centurylinklabs.watchtower.enable=1

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    command: --cleanup --label-enable --interval 30
    restart: always
    env_file: ./watchtower/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  app-network:
    driver: bridge